### ISSUE TITLE
Two main threads

### ISSUE THREAD

**Issue by erolisdev** [VNAPNIC/presentation-displays#37]
Is it normal that when I add this package to my application and run showSecondaryDisplay two main threads are created?
![image](https://github.com/VNAPNIC/presentation-displays/assets/91616806/95d2fe4c-4e90-4651-a6c5-2b4405c7d9fd)

**Comment by ravindran-a** [comment]
@schigabiga how do we do this for iOS as well. Can you please help?

**Comment by smew-tech** [comment]
resolved issue: v1.0.0

**Comment by ravindran-a** [comment]
@VNAPNIC this is not resolved for iOS yet. Can you help on that please
